"""Token and dollar cost estimation for a RAG query.

Rates are per 1,000,000 tokens. UPDATE THESE to current published pricing
before using for real budgeting -- they drift as providers change plans.
"""

from __future__ import annotations

from typing import TypedDict

# Default rates, USD per 1M tokens. Snapshot as of the model's known public
# pricing at the time this file was written (Claude 3.5 Sonnet-class pricing,
# Voyage-class embeddings). UPDATE TO CURRENT PRICING before relying on this
# for real cost forecasts -- provider pricing changes over time.
DEFAULT_RATES = {
    "input_usd_per_million": 3.00,
    "output_usd_per_million": 15.00,
    "embed_usd_per_million": 0.10,
}


class CostBreakdown(TypedDict):
    input_tokens: int
    output_tokens: int
    embed_tokens: int
    total_tokens: int
    input_usd: float
    output_usd: float
    embed_usd: float
    total_usd: float


def estimate_cost(
    input_tokens: int,
    output_tokens: int,
    embed_tokens: int,
    rates: dict | None = None,
) -> CostBreakdown:
    """Estimate token counts and USD cost for a single RAG query.

    Args:
        input_tokens: prompt tokens sent to the generation model (retrieved
            context + query + system prompt).
        output_tokens: tokens generated by the model in its answer.
        embed_tokens: tokens sent to the embedding model for the query
            (and, if applicable, any documents embedded at query time).
        rates: optional override dict with keys matching DEFAULT_RATES.
            Missing keys fall back to DEFAULT_RATES.

    Returns:
        Dict with token counts and USD breakdown, including total_usd.

    Raises:
        ValueError: if any token count is negative.
    """
    for name, value in (
        ("input_tokens", input_tokens),
        ("output_tokens", output_tokens),
        ("embed_tokens", embed_tokens),
    ):
        if value < 0:
            raise ValueError(f"{name} must be non-negative, got {value}")

    merged_rates = {**DEFAULT_RATES, **(rates or {})}

    input_usd = input_tokens * merged_rates["input_usd_per_million"] / 1_000_000
    output_usd = output_tokens * merged_rates["output_usd_per_million"] / 1_000_000
    embed_usd = embed_tokens * merged_rates["embed_usd_per_million"] / 1_000_000

    return {
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "embed_tokens": embed_tokens,
        "total_tokens": input_tokens + output_tokens + embed_tokens,
        "input_usd": input_usd,
        "output_usd": output_usd,
        "embed_usd": embed_usd,
        "total_usd": input_usd + output_usd + embed_usd,
    }
